all:
  vars:
    environment: test  # Variable définissant l'environnement dans lequel le playbook sera exécuté (ici, "test").
    gateway_srv_ip: "51.159.178.194"  # Adresse IP du serveur gateway (passerelle).
    gateway_srv_subnet: "172.16.16.2/22"  # Sous-réseau associé au serveur gateway.
    gateway_client_ip: "51.159.162.252"  # Adresse IP du client gateway.
    gateway_client_subnet: "172.16.20.2/22"  # Sous-réseau associé au client gateway.
    psk: "pH56SwETVACv0FaMjPv28fH3Jkq6PVqeeRCvlTZtKCk="  # Clé pré-partagée (PSK) utilisée pour l'authentification IPsec.

  children:
    debian_srv:
      hosts:
        51.159.178.194:
          ansible_user: root  # Hôte du groupe "debian_srv", spécifiant l'utilisateur "root" pour les connexions Ansible.
          
    debian_client:
      hosts:
        51.159.162.252:
          ansible_user: root  # Hôte du groupe "debian_client", spécifiant également "root" comme utilisateur Ansible.


# pour verifier la connection avec les instance 
# ansible --private-key "private-key-path" -i hosts.yml (debian_srv ou debian_client) -m ping

# pour executer le code
# ansible-playbook --private-key "private-key-path" -i hosts.yml env-test.yml
# rappel : ansible doit etre executer dans wsl 